//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject_jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompJobVacc_Tab
    {
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public string Skills { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string Salary_Range { get; set; }
        public string Job_Type { get; set; }
        public System.DateTime Posted_Date { get; set; }
        public System.DateTime Last_Date { get; set; }
        public string Status { get; set; }
    }
}
